# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    container_name: mysql_chocolicia
    command: --default-authentication-plugin=mysql_native_password
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=desenv
      - MYSQL_DATABASE=chocoalicia
    ports:
      - "3306:3306"